# Generated by Django 4.0.4 on 2022-10-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('op_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=50)),
                ('model_no', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=50)),
                ('cpu_type', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('disk_size', models.CharField(max_length=50)),
                ('disk_type', models.CharField(max_length=50)),
                ('point', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('site_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'scrape',
            },
        ),
    ]
