# Generated by Django 4.0.4 on 2022-10-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_scrape_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scrape',
        ),
    ]
