# Generated by Django 4.0.4 on 2022-10-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraping', '0004_delete_scrape'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('product_id', models.TextField(primary_key=True, serialize=False)),
                ('brand', models.TextField()),
                ('model_name', models.TextField()),
                ('model_no', models.TextField()),
                ('photo_1', models.TextField()),
                ('photo_2', models.TextField()),
                ('photo_3', models.TextField()),
                ('photo_4', models.TextField()),
                ('photo_5', models.TextField()),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('product_id', models.TextField(primary_key=True, serialize=False)),
                ('os', models.TextField()),
                ('cpu', models.TextField()),
                ('cpu_gen', models.TextField()),
                ('ram', models.TextField()),
                ('ssd_size', models.TextField()),
                ('hdd_size', models.TextField()),
                ('screen_size', models.TextField()),
            ],
            options={
                'db_table': 'hardware',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('product_id', models.TextField(primary_key=True, serialize=False)),
                ('product_point', models.IntegerField()),
                ('price', models.IntegerField()),
                ('website', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'site_info',
            },
        ),
    ]
