# Generated by Django 4.0.4 on 2022-10-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Hardware',
        ),
        migrations.DeleteModel(
            name='SiteInfo',
        ),
    ]
