# Generated by Django 4.0.4 on 2022-10-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='url',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
