# Generated by Django 4.0.4 on 2022-10-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0010_remove_siteinfo_id_alter_siteinfo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='product_point',
            field=models.TextField(),
        ),
    ]
