# Generated by Django 4.0.4 on 2022-10-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0013_alter_siteinfo_price_alter_siteinfo_product_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='photo1',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='photo5',
        ),
    ]
