# Generated by Django 4.0.4 on 2022-10-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0014_rename_photo1_brand_photo_remove_brand_photo2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Hardware',
        ),
        migrations.DeleteModel(
            name='SiteInfo',
        ),
    ]
