# Generated by Django 4.0.4 on 2022-10-20 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0016_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scraping.brand'),
        ),
    ]
