# Generated by Django 4.0.4 on 2022-10-20 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0017_alter_hardware_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scraping.hardware'),
        ),
    ]
