# Generated by Django 4.0.4 on 2022-10-20 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraping', '0019_remove_hardware_url_remove_siteinfo_url_delete_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('url', models.TextField(primary_key=True, serialize=False)),
                ('brand', models.TextField()),
                ('model_name', models.TextField()),
                ('model_no', models.TextField()),
                ('photo', models.TextField()),
                ('product_point', models.TextField()),
                ('price', models.TextField()),
                ('website', models.TextField()),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scraping.brand')),
                ('os', models.TextField()),
                ('cpu', models.TextField()),
                ('cpu_gen', models.TextField()),
                ('ram', models.TextField()),
                ('ssd_size', models.TextField()),
                ('hdd_size', models.TextField()),
                ('screen_size', models.TextField()),
            ],
            options={
                'db_table': 'components',
            },
        ),
    ]
