# Generated by Django 4.0.4 on 2022-10-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0020_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='url',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
