# Generated by Django 4.0.4 on 2022-10-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0021_alter_components_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Components',
        ),
    ]
