# Generated by Django 4.0.4 on 2022-10-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraping', '0022_delete_brand_delete_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('url', models.TextField(primary_key=True, serialize=False)),
                ('brand', models.TextField()),
                ('model_name', models.TextField()),
                ('model_no', models.TextField()),
                ('photo', models.TextField()),
                ('product_point', models.TextField()),
                ('price', models.TextField()),
                ('website', models.TextField()),
                ('os', models.TextField()),
                ('cpu', models.TextField()),
                ('cpu_gen', models.TextField()),
                ('ram', models.TextField()),
                ('ssd_size', models.TextField()),
                ('hdd_size', models.TextField()),
                ('screen_size', models.TextField()),
            ],
            options={
                'db_table': 'brand',
            },
        ),
    ]
