# Generated by Django 4.0.4 on 2022-10-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0023_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='hdd_size',
            new_name='disk_capacity',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='ssd_size',
        ),
    ]
