# Generated by Django 4.0.4 on 2022-10-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0024_rename_hdd_size_brand_disk_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='price',
            field=models.IntegerField(),
        ),
    ]
