# Generated by Django 4.0.4 on 2022-10-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0027_alter_brand_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='brand',
            name='website',
            field=models.TextField(),
        ),
    ]
